name: Python build c extension
description: Python build c extension tests
inputs: 
  python:
    description: version of python
    required: true
    default: "none"
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4.7.0
      with:      
        python-version: ${{ inputs.python }}

    - name: Install dependencies
      shell: bash
      working-directory: 'src/python/c-extension/'
      run: |
        python -m pip install --upgrade pip
        pip install wheel

    - name: make
      shell: bash
      working-directory: 'src/python/c-extension/'
      run: make