name: Invoke tests
inputs:
  uses:
    description: 'Path to the tses e.g. `.github/actions/7zip`'
    required: true
  with:
    description: 'JSON-ified `inputs` for the action, e.g. `{"python": "3.8"}`'
    required: false
    default: "{}"
outputs:
  outputs:
    value: ${{ steps.run.outputs.outputs }}
runs:
  using: composite
  steps:
    - name: Setup
      shell: pwsh
      run: |
        New-Item -Path ./.tmp-invoke-tests -ItemType "Directory" -Force
        $actionYml = @'
        outputs:
          outputs:
            value: ${{ '$' }}{{ toJSON(steps.run.outputs) }}
        runs:
          using: composite
          steps:
          - name: Run
            id: run
            uses: ${{ inputs.uses }}
            with: ${{ inputs.with || '{}' }}
        '@ | Out-File ./.tmp-invoke-tests/action.yml
    - name: Run
      id: run
      uses: ./.tmp-invoke-tests
    - name: Cleanup
      if: always()
      shell: bash
      run: rm -rf ./.tmp-invoke-tests
