name: macOS image generation
on:
  workflow_call:
    inputs:
      image_label:
        type: string
        description: macOS codename
        required: true
      base_image_name:
        type: string
        description: Base clean image
        required: true
      virtualMachineName:
        type: string
        description: Name for VM in vSphere
        required: true
      template_path:
        type: string
        description: Packer template path
        required: true
      target_datastore:
        type: string
        description: Image datastore
        required: true
      custom_repo:
        type: string
        description: Custom repo to checkout
        required: false
      custom_repo_hash:
        type: string
        description: Custom repo hash
        required: false

env:
  KEYVAULT: imagegeneration
  ESXI_CLUSTER: mcv2-build-unstable
  VCENTER_DATACENTER: imagegen
  OUTPUT_FOLDER: mms-output
  BUILD_DATASTORE: ds-image

defaults:
  run:
    shell: pwsh
    
jobs:
  build:
    runs-on: maccloudv2
    steps:
    - name: set Virtual Machine Name
      shell: pwsh
      run: |
        #$virtualMachineName = ${{ inputs.virtualMachineName }}
        #echo "current_date=$todayte" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        write-host ${{ inputs.virtualMachineName }}
               
    - uses: actions/checkout@v3
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Validate contributor permissions
      #if: ${{ startsWith(github.ref, 'refs/pull/') == true }}
      if: ${{ github.event_name == 'pull_request_target' }}
      run: |
        $GitHubFeed = az keyvault secret show -n "github-feed-token" --vault-name "${{ env.KEYVAULT }}" --query value -o tsv
        [string]$contributorAllowList = "${{ vars.CONTRIBUTOR_ALLOWLIST }}"
        ./images.CI/macos/validate-contributor.ps1 `
          -RepositoryName ${{ github.repository }} `
          -AccessToken $GitHubFeed `
          -SourceBranch "refs/pull/${{ github.event.pull_request.number }}/merge" `
          -ContributorAllowList $contributorAllowList
        
        
    - name: Select datastore
      run: |
        $VIUserName = az keyvault secret show -n "vcenter-username-v2" --vault-name "${{ env.KEYVAULT }}" --query value -o tsv
        $VIPassword = az keyvault secret show -n "vcenter-password-v2" --vault-name "${{ env.KEYVAULT }}" --query value -o tsv
        
        ./images.CI/macos/select-datastore.ps1 `
          -VMName "${{ inputs.virtualMachineName }}" `
          -VIServer ${{ secrets.VISERVER_V2 }} `
          -VIUserName $VIUserName `
          -VIPassword $VIPassword `
          -Cluster ${{ env.ESXI_CLUSTER }}
        
    - name: Build VM
      run: |
        $VIUserName = az keyvault secret show -n "vcenter-username-v2" --vault-name "${{ env.KEYVAULT }}" --query value -o tsv
        $VIPassword = az keyvault secret show -n "vcenter-password-v2" --vault-name "${{ env.KEYVAULT }}" --query value -o tsv
        $XcodeUser = az keyvault secret show -n "xcode-installation-user" --vault-name "${{ env.KEYVAULT }}" --query value -o tsv
        $XcodePassword =  az keyvault secret show -n "xcode-installation-password" --vault-name "${{ env.KEYVAULT }}" --query value -o tsv
        
        $SensitiveData = @(
          'IP address:',
          'Using ssh communicator to connect:'
        )
         packer build -on-error=abort `
        -var="vcenter_server=${{ secrets.VISERVER_V2 }}" `
        -var="vcenter_username=$VIUserName" `
        -var='vcenter_password=$VIPassword' `
        -var="vcenter_datacenter=${{ env.VCENTER_DATACENTER }}" `
        -var="cluster_or_esxi_host=${{ env.ESXI_CLUSTER }}" `
        -var="esxi_datastore=${{ env.BUILD_DATASTORE }}" `
        -var="output_folder=${{ env.MMS_OUTPUT }}" `
        -var="vm_username=${{ secrets.VM_USERNAME }}" `
        -var="vm_password=${{ secrets.VM_PASSWORD }}" `
        -var="github_api_pat=${{ secrets.GH_FEED_TOKEN }}" `
        -var="build_id=${{ inputs.virtualMachineName }}" `
        -var="baseimage_name=${{ inputs.base_image_name }}" `
        -var="xcode_install_user=$XcodeUser" `
        -var="xcode_install_password=$XcodePassword" `
        -color=false `
        ${{ inputs.template_path }} `
        | Where-Object {
            #Filter sensitive data from Packer logs
            $currentString = $_
            $sensitiveString = $SensitiveData | Where-Object { $currentString -match $_ }
            $sensitiveString -eq $null
        }
      working-directory: images/macos
      env:
        PACKER_LOG: 1
        PACKER_LOG_PATH: ${{ runner.temp }}/packer-log.txt
