run-name: matrix-run
on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        description: 'image version'
        required: false

jobs:
  matrix-tes:
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_name: test 1
            test_path: ./.github/workflows/triggered1.yml
          
          - test_name: test 2
            test_path: ./.github/workflows/triggered2.yml
          
          - test_name: test 3
            test_path: ./.github/workflows/triggered3.yml
            
    name: run all tests
    runs-on: ubuntu-latest
    steps:
      - name: test1
        uses: ./.github/workflows/triggered1.yml
        with:
          IMAGE_NAME: "AzP.20230630.win22.1"
            
