run-name: matrix-run
on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        description: 'image version'
        required: false

jobs:
  matrix-tes:
    strategy:
      fail-fast: false
      matrix:
        include:
          - test_name: test 1
            test_path: ./.github/actions/7zip
          
          - test_name: test 2
            test_path: ./.github/actions/azsecpacl-ubnt
          
            
    name: run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: ${{ matrix.test_name }}
        uses: ${{ matrix.test_path }}

            
