on:
  workflow_call

permissions:
      id-token: write
      contents: read
      
jobs: 
  Windows-latest:
      runs-on: windows-latest
      steps:
        - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
          uses: azure/login@v1
          with:
            client-id: ${{ secrets.CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION }} 
            enable-AzPSSession: true

        - name: 'Get resource group with PowerShell action'
          uses: azure/powershell@v1
          with:
             inlineScript: |
               #Get-AzResourceGroup
               New-AzResourceGroup -Name "RG-OpenID-Test" -Location "South Central US"
             azPSVersion: "latest"
