run-name: call reusable wf
on:
  workflow_dispatch:
  
  pull_request_target:
    types: labeled

jobs:
  wf-call:
    name: invoke openid via reusable wf
    uses: ./.github/workflows/openid-test.yml
    with:
      image_name: 'ubuntu2004'
    secrets: inherit
