run-name: triggered one
on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        description: 'image version'
        required: false

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    name: trigger test
    steps:
      - name: trigger 1  
        shell: pwsh  
        run: |
          write-host "it works"
