run-name: tigger
on:
  workflow_dispatch:
    inputs:
      IMAGE_VERSION:
        description: 'image version'
        required: false

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    name: trigger test
    steps:
      - name: trigger 1  
        shell: pwsh  
        run: |
          $base64AuthInfo = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("'':${{ secrets.TEST_PAT }}"))
          $headers = @{Authorization="Basic $base64AuthInfo"}

          $WorkflowId = "triggered.yml"
          $imageName= "AzP.20230630.win22.1"
          $url = "https://api.github.com/repos/AleAiu/simpletest/actions/workflows/${WorkflowId}/dispatches"
                    $body = @{
                      ref = "main"
                      inputs = @{
                          IMAGE_NAME = "$imageName"
                           }
                        } | ConvertTo-Json

          Invoke-RestMethod -Method Post `
          -Uri $url `
          -Headers $headers `
          -Body $body

